### ISSUE TITLE
watchAll should make the connection subscribe to newly added accounts

### ISSUE THREAD

**Issue by jtmoulia** [thusfresh/switchboard#47]
The title says it all.

Thanks to @ostera for finding this.

**Comment by ostera** [comment]
Hey @jtmoulia, I'll be able to start working on this tonight/tomorrow. Wondering if you could give me some pointers on what to look for or where to get started?

About the interface, should the `watchAll` message take a param to watch subsequent connections? –to maintain backwards compatibility

**Comment by jtmoulia** [comment]
Hey @ostera,

Awesome. Check out [switchboard_accounts_sup:start_child/3](https://github.com/thusfresh/switchboard/blob/master/src/switchboard_accounts_sup.erl#L69). More info to come, and I'll be sitting around on irc.freenode.net at #switchboard-dev and can chat.

> About the interface, should the watchAll message take a param to watch subsequent connections? –to maintain backwards compatibility

I like the default of subscribing to subsequent connections, so my vote goes with not maintaining backwards compatibility. Really, it's more of a bug. Potentially we could add a param for _not_ watching accounts which connect subsequently, but I'd like to wait until we have real use-cases for that.

**Comment by ostera** [comment]
From what I understand so far:

1. the accounts supervisor starts up

2. every time an account is added, a new account child process is created which by convention when using the supervisor behaviour would be a switchboard_accounts process, right?

3. at this point, `switchboard_accounts:start_link/3` is called by the supervisor:start_child call from `switchboard_accounts_sup:start_child/3`, and that starts a link that will call the `switchboard_accounts:init/1` function, where the actual child is spawn and set up

4. then the `switchboard:register_callback/2` is called, registering the account's process in gproc

And on a separate time-line, another client connects to Switchboard and sends a watchAll command (which from what I see on the JMAP spec it's a switchboard feature).

This command get's handled at `switchboard_workers:call_all/3` where the first element of the first tuple of the list passed as the first argument is the binary string `<<"watchAll">>`, and it's handled by calling `switchboard:subscribe(new)`.

So if I'm understanding this correctly, watchAll would only subscribe to new mail on a given account's process, and what we need to do here is to call watchAll for all subsequent new account processes that get spawned by the `switchboard_accounts_sup:start_child/3` **after** a watchAll has been sent by any given client.

The question then becomes: is there a use-case for not watching new mail for all registered accounts within switchboard?

And also: should I save in gproc a state variable like `watching_all` that is checked right after spawning a new `switchboard_account` child and if true, then immediately call `switchboard:subscribe(new)` on that process?

Let me know if my train of thought is on the right direction, @jtmoulia

**Comment by jtmoulia** [comment]
Hey, sorry, on the road, but the current design should be working --
switchboard:subscribe(new) subscribes to new messages across _all_
accounts. It should only need to be called once from a process.

I fixed a different bug the other day that might've been causing the
behavior you were seeing. Let me know

**Comment by ostera** [comment]
Perfect. Then by setting a gproc global variable I should be able to know whether `watchAll` has been called already and then just re-call `switchboard:subscribe(new)` any time a new account is added by `switchboard_account_sup:start_child/3`.

**Comment by jtmoulia** [comment]
Heh, sorry -- my message was ambiguous: I believe that the watchAll problem
you saw was due to a different cause (new message UID comparison). I've
successfully tested adding accounts after calling watchAll with the latest
in master, and if things work for you we can close this issue.

Internally, switchboard uses a gproc based pubsub system to implement
watchAll: all processes that call switchboard:subscribe(new) will
subsequently receive all messages published by switchboard:publish(new,
...) until they die or unsubscribe. Given that all accounts publish new
messages to this 'new' topic, one subscribe call should be enough.

Hopefully that makes sense!

**Comment by ostera** [comment]
Oh, that makes sense. I'll update to master and get back to close this issue

**Comment by jtmoulia** [comment]
<3 + thanks for your patience @ostera

**Comment by ostera** [comment]
Yup! Seems to be working quite well.

/closed
