### ISSUE TITLE
Relx overlays

### ISSUE THREAD

**Issue by tsloughter** [thusfresh/switchboard#49]
I'm searching and asking around about peoples use of overlays in relx because I'd like to replace erlydtl with mustache. Some details here, https://t.co/hyuJCXWsff

Searching github I found you use an erlydtl feature that isn't in mustache here: https://github.com/thusfresh/switchboard/blob/master/files/app.config#L17

So I wanted to reach out and check if this would be a problem, if you really needed that feature, and figure out where to go from there.

**Comment by jtmoulia** [comment]
Posted a response -- in sum, no problem. I'll keep an eye on where relx heads re templating.
